export type BookingErrorCode =
  | 'SLOT_NOT_FOUND'
  | 'SLOT_CLOSED'
  | 'SLOT_FULL'
  | 'PAST_CUTOFF'
  | 'INVALID_ITEMS'
  | 'PARTY_TOO_LARGE'
  | 'PARTY_TOO_SMALL'
  | 'CONTACT_REQUIRED'
  | 'DUPLICATE_BOOKING'
  | 'RATE_LIMITED'
  | 'BOOKING_NOT_FOUND'
  | 'NOT_CANCELLABLE'
  | 'REFUND_REQUIRED'
  | 'GUEST_COUNT_REQUIRED'
  | 'GUEST_COUNT_TOO_LARGE'
  | 'AGREEMENT_REQUIRED'
  | 'AGES_REQUIRED'
  | 'BOOKING_PAUSED'
  | 'MENU_PAUSED'
  | 'INVALID_TRANSITION'
  | 'PAYMENT_REQUIRED'
  | 'OPERATOR_NOT_FOUND'
  | 'SAME_SLOT'
  | 'NOT_STARTED'
  | 'REFUND_TOO_LARGE'
  | 'PAYMENT_INSTRUCTIONS_MISSING'
  | 'OPERATOR_SUSPENDED'
  | 'OPERATOR_LOCKED'
  | 'OPERATOR_REQUIRED'
  | 'OPERATOR_DECLINED'
  | 'OPERATOR_UNCONFIRMED';

export class BookingError extends Error {
  constructor(readonly code: BookingErrorCode) {
    super(code);
    this.name = 'BookingError';
  }
}
